### ISSUE TITLE
Notes (if you still interested/supporting the project)

### ISSUE THREAD

**Issue by asigalov61** [magenta/listen-to-transformer#3]
I love your solution for many reasons. It was genius and yet simple, right?!? :) 

I wanted, however, to provide some critical feedback...

I would at the very least make the player take full-screen as you can barely see the player, let alone the visualization, which is a shame cuz its great.

The color scheme/background should be more classical/stylish since its a classical piano AI model.

I would rethink visualization (it should not be abstract, it should be classical) or at the very least make it adjustable in code somewhere somehow.

Make it easily adjustable for users' midi files collection (done in issues but not integrated into the release).

Clearly labeled and explained code cuz I could not understand it. Sorry.

And I could really use the tutorials on how to deploy it easily and quickly either on your Google Cloud or say something like Heroku/PaperSpace...

So if you guys (or someone) can do it, it will be very useful and much appreciated.

P.S. The player demo is buried on the 3rd level of your magenta main site. This is a big mistake IMHO because your Piano Transformer model is absolutely amazing :) It should be on the main page, front, center, and full-screen IMHO.

MusicVUE model is even better but it's not working (for users) so the only choice atm for users is to use the Piano Transformer and be limited by 1 instrument :(

Hope this is helpful and sorry for so many suggestions but I love music and I want to see Music AI done right.

Thanks.

AS

**Comment by notwaldorf** [comment]
Thanks for the feedback! We are not really maintaining this project at the moment (in the sense that we would fix bugs, but nothing more than that)

For deploying, we really don't do anything special, which is why it's not documented. The entire site is just html and css and very little js, so what you see is what it's hosted (we are literally just using the GitHub UI to have the master branch be automatically deployed gh-pages), so there's no infra around it.
